# Generated by Django 4.2.1 on 2023-06-27 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0002_alter_comment_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
