# Generated by Django 4.2.1 on 2023-06-29 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
