# Generated by Django 4.2.1 on 2023-07-04 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_tasks_description_alter_tasks_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'verbose_name_plural': 'Task'},
        ),
    ]
