# Generated by Django 3.2.12 on 2023-05-28 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_jobpost_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='author',
        ),
    ]
