# Generated by Django 3.2.12 on 2023-05-28 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_alter_jobpost_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='author',
            new_name='name',
        ),
    ]
