# Generated by Django 3.2.12 on 2023-05-28 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0008_remove_jobpost_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='name',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
