# Generated by Django 3.2.12 on 2023-05-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_alter_jobpost_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='qualification',
            field=models.TextField(),
        ),
    ]
