# Generated by Django 4.2.1 on 2023-06-06 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_alter_blogpost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(default='Uncategorized', max_length=150),
        ),
    ]
