# Generated by Django 4.2.1 on 2023-06-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_alter_blogpost_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='headline',
            field=models.TextField(default='The post headline', max_length=255),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(max_length=150),
        ),
    ]
