# Generated by Django 4.2.1 on 2023-06-13 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0025_profile_instagram_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
