# Generated by Django 4.2.1 on 2023-06-16 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0030_remove_comment_name_comment_parent_comment_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
