# Generated by Django 4.2.1 on 2023-07-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0037_blogpost_draft_blogpost_scheduled_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
