# Generated by Django 4.2.1 on 2023-07-01 17:55

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0038_blogpost_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='draft',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='published',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='scheduled_publish_date',
        ),
        migrations.CreateModel(
            name='SaveAsDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(default='uncategorized', max_length=150)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, unique=True)),
                ('headline', models.TextField(max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
