# Generated by Django 4.2.1 on 2023-07-04 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0039_remove_blogpost_draft_remove_blogpost_published_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'verbose_name_plural': 'Blog Category'},
        ),
    ]
