# Generated by Django 4.2.1 on 2023-07-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0040_alter_blogcategory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='saveasdraft',
            name='category',
            field=models.CharField(max_length=150),
        ),
    ]
