# Generated by Django 4.2.1 on 2023-06-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_jobpost_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='location',
            field=models.CharField(default='unknown', max_length=150),
        ),
    ]
