# Generated by Django 4.2.1 on 2023-06-24 22:15

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_jobpost_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='location',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='JobComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_comments', to='job.jobpost')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
