# Generated by Django 4.2.1 on 2023-07-04 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_alter_jobcomment_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobcategory',
            options={'verbose_name_plural': 'Job Category'},
        ),
    ]
