# Generated by Django 4.2.1 on 2023-07-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_alter_jobcategory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='category',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='deadline',
            field=models.DateTimeField(),
        ),
    ]
