# Generated by Django 4.2.5 on 2023-10-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_alter_jobsaveasdraft_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
